services:
  - type: web
    name: swiftery-backend
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVars:
      - key: MONGODB_URI
        scope: run
        value: ${MONGODB_URI}
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: "https://swiftery.pages.dev"
      - key: IPINFO_TOKEN
        value: ${IPINFO_TOKEN}
      - key: GOOGLE_MAPS_API_KEY
        value: ${GOOGLE_MAPS_API_KEY}
    rootDir: Backend
